services:

  backend:
    build: ./backend
    container_name: pdf_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/pdf_db
    volumes: 
      - /home/oucht/pdf-tma-app/backend/app/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  postgres:
    image: postgres:13
    container_name: pdf_postgres
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pdf_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: pdf_redis
    ports:
      - "6379:6379"

  frontend: 
    build: ./frontend
    container_name: pdf_frontend
    ports:
      - "5173:5173"
    depends_on: 
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pdf_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: user
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data: