version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pdf_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:pass@postgre:5432/pdf_db
    depends_on:
      - postgres
      - redis


