version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pdf_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://user:pass@postgres:5432/pdf_db
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    container_name: pdf_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pdf_db
    ports: 
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  redis:
    image: redis
    container_name: pdf_redis
    ports:
      - "6379:6379"

  frontend: 
    build: ./frontend
    container_name: pdf_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on: 
      - backend

volumes:
  pg_data: